### ISSUE TITLE
Too few arguments to function plgSystemAstroid::onContentBeforeSave() - Menu Modification

### ISSUE THREAD

**Issue by GreezeLee** [templaza/astroid-framework#177]
Since Astroid Framework Version V2.5.19, the following error appears if I create or modify an existing menu item:

Too few arguments to function plgSystemAstroid::onContentBeforeSave(), 3 passed in .../httpdocs/libraries/joomla/event/event.php on line 70 and exactly 4 expected.

Downgrade to Astroid Framework 2.5.18 solves the problem.

Joomla Version: Joomla! 3.10.11 
PHP Version: 7.4.30

**Comment by Chacapamac** [comment]
Mark as bug.

Working correctly on my Joomla 4.2 — Astroid 2.5.19 framework and templates zero/one - PHP 8.1.9

**Comment by sonvnn** [comment]
@GreezeLee @Chacapamac I fixed this issue in https://github.com/templaza/astroid-framework/commit/4f46fd47ea54cd83f2bdc6c0ff04c30b08304d41 
Please help me download developer branch and test it again.

Thanks & Best Regards,
Sonny

**Comment by GreezeLee** [comment]
It works!
Thank you!
Best regards
Andreas

**Comment by Chacapamac** [comment]
• Just try **Joomla 3.10.10 - PHP 7.4.21 - Astroid 2.5.18** — **No problems with menu modifications**

• **Install Astroid 2.5.18**
_**Changing menus bring this error** (Rest of admin fully functional)_
_Too few arguments to function plgSystemAstroid::onContentBeforeSave(), 3 passed in /......../libraries/joomla/event/event.php on line 70 and exactly 4 expected_ 

• **Update Joomla 3.10.11 = Same error**

• **Install Dev Branch**  **_(Astroid Framework & Plugin 2.5.20)_**

NO ERRORS!
