### ISSUE TITLE
00 Error After Updating Astroid Framework and Saving Template Settings (Joomla 5, PHP 8.3, Astroid 3.1.12, Jollyany 3.5.35)

### ISSUE THREAD

**Issue by Geri-X** [templaza/astroid-framework#1055]
### **Describe the bug**
After updating **Astroid Framework to 3.1.12** on a Joomla 5 installation with PHP 8.3, the website throws a **500 error** when saving the **Today News (Jollyany 3.5.35) template settings**.

Additionally, attempting to **compile SCSS** results in an error due to an **undefined variable `$main-border-color`** in `astroid.scss`, which prevents styles from loading correctly.

#### **Error Messages**
1. **500 Internal Server Error** (after saving template settings).
2. **SCSS Compilation Error**:
   ```
   Undefined variable $main-border-color: libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tz_todaynews/scss/jollyany/astroid.scss on line 4, at column 3
   Call Stack:
   #0 import libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tz_todaynews/scss/jollyany/astroid.scss 
      libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tz_todaynews/scss/style.scss on line 3
   #1 import libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tz_todaynews/scss/style.scss (unknown file) on line 1
   ```

---

### **To Reproduce**
1. Update Joomla 5 to **Astroid Framework 3.1.12**.
2. Navigate to **Template Settings** (Jollyany - Today News).
3. Click **Save** without making any changes.
4. The site immediately throws a **500 error**.
5. If attempting to compile SCSS, the `$main-border-color` error appears.

---

### **Expected Behavior**
- The template settings should save without causing a **500 error**.
- SCSS should compile without missing variable errors.
- `$main-border-color` should be defined before use in `astroid.scss`.

---

### **System Information**
- **Joomla Version:** 5.0.x
- **PHP Version:** 8.3
- **Astroid Version:** 3.1.12
- **Jollyany Version:** 3.5.35
- **Template:** Today News
- **Test Server:** [https://test.korosten.today/](https://test.korosten.today/)

**Comment by felixkat** [comment]
What version is your template?  Looks like there was a an update in February, version 1.0.2 

https://www.templaza.com/download/joomla-templates/tz_membership/downloadinfo/322-tz-todaynews.html

I don't have access to templaza so I cannot test, but it looks like it's an issue with the template rather than the frameworks, (don't quote me on that though).

**Comment by Geri-X** [comment]
> What version is your template? Looks like there was a an update in February, version 1.0.2
> 
> https://www.templaza.com/download/joomla-templates/tz_membership/downloadinfo/322-tz-todaynews.html
> 
> I don't have access to templaza so I cannot test, but it looks like it's an issue with the template rather than the frameworks, (don't quote me on that though).

Template Version 1.0.2
Through trial and error I have determined that this error occurs after updating the astroid framework.

**Comment by sonvnn** [comment]
It is an issue of Template. I will update Today News to fix it today. Please wait for updating. At the moment you can downgrade your Astroid to your last version for running website.

**Comment by sonvnn** [comment]
@Geri-X This issue occurs when the `$main-border-color` variable is missing in Template Options.
You need to check in Template options -> Theming -> Sass Overrides

Make sure the `main-border-color` variable still exists.

Please check the screenshot below. I updated Todaynews with Astroid 3.1.12 and everything works as expected.

![Image](https://github.com/user-attachments/assets/a1be9738-f3a5-4501-8632-8e49282639ca)

If this issue is still happen. Please send me your admin acc via sonlv@templaza.com. I will help you check.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@Geri-X I updated Todaynews to 1.0.3. You can download it and upload to your site to fix this issue.
Best Regards,
Sonny

**Comment by Geri-X** [comment]
Now everything is working as it should! Thanks for the fix
